#!/bin/bash
# @author ricardo-melo-martins
# @license MIT
set -euo pipefail

export readonly RED="\033[0;31m"
export readonly GREEN="\033[0;32m"
export readonly BLUE="\033[0;34m"
export readonly NOCOLOR="\033[0m"
